- name: Generate manpage
  if: runner.os != 'Windows'
  shell: bash
  run: |
    set -euo pipefail
    out_dir="dist/share/man/man1"
    mkdir -p "$out_dir"
    cargo run --bin mandate -- -i docs/mandate.yml -p mandate -s 1 -t "Mandate Manual" -o "$out_dir/mandate.1"
